name: quark
version: 0.0.1
description: An extensive testing library.
author: Emil Persson <emil.n.persson@gmail.com> @emilniklas
homepage: https://emilpersson.se
environment:
  sdk: '>=1.9.0 <2.0.0'
#dependencies:
#  foo_bar: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: any
