name: quark
version: 0.3.0
description: Full featured testing framework
author: Emil Persson <emil.n.persson@gmail.com>
homepage: https://github.com/emilniklas/quark
environment:
  sdk: ">=1.12.0 <2.0.0"
dependencies:
  test: ">=0.1.0 <1.0.0"
  tuple: ^1.0.0
  reflectable: ^0.5.0
  path: ^1.0.0
dev_dependencies:
  dart_coveralls: any
transformers:
- reflectable:
    $include: test/**_test.dart
    entry_points:
      - test/contexts/html_test.dart
      - test/gherkin/external_feature/external_html_test.dart
      - test/gherkin/external_feature/external_io_test.dart
      - test/integration_test.dart
      - test/test_double_test.dart
      - test/test_test.dart
      - test/unit_test.dart
      - test/timeline_hook_methods_test.dart
    formatted: true
- test/pub_serve:
    $include: test/**_test.dart
- $dart2js:
    $include: test/**_test.dart
