name: quark
version: 0.1.0
description: Full featured testing framework
author: Emil Persson <emil.n.persson@gmail.com>
homepage: https://github.com/emilniklas/quark
environment:
  sdk: ">=1.12.0 <2.0.0"
dependencies:
  test: ">=0.12.6+2 <1.0.0"
  tuple: ^1.0.0
  reflectable: ^0.5.1
dev_dependencies:
  testcase: any